language: c++
sudo: required
dist: xenial

addons: &addons
  apt:
    sources: &sources
      - ubuntu-toolchain-r-test
    packages: &packages
      - libfaad-dev
      - libfdk-aac-dev
      - libmpg123-dev
      - libsdl2-dev
      - libgtkmm-3.0-dev
      - g++-9

script:
  - |
    mkdir build_faad
    pushd build_faad
    cmake -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9 ..
    make
    sudo make install
    popd
  - |
    mkdir build_fdkaac
    pushd build_fdkaac
    cmake -DUSE_FDK-AAC=1 -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9 ..
    make
    sudo make install
    popd
